package main

func main() {
	// fmt.Println("Hello, World!")
	// latVariable()
	// latAlias() 
	// latConst()
	// latIO_output()
	// latOperator()
	// latJenisOperator()
	// latIF()
	// latIFShortStt()
	// latSwitch()
	// latSwitch2()
	// latSwitch3()
	// latLoop1()
	// latLoop2()
	// latLoop3()
	// fmt.Println(divide(10, 3))
	// fmt.Println(getCoordinates())
	// latArray()
	// latArray2()
	// latSlice1()
	// latSlice2()
	// latSlice3()
	// latSlice4()
	latSlice5()
}