package main

func main() {
	// fmt.Println("Hello, World!")
	// latVariable()
	// latAlias() 
	// latConst()
	// latIO_output()
	// latOperator()
	// latJenisOperator()
	// latIF()
	// latIFShortStt()
	// latSwitch()
	// latSwitch2()
	// latSwitch3()
	// latLoop1()
	// latLoop2()
	// latLoop3()
	// fmt.Println(divide(10, 3))
	// fmt.Println(getCoordinates())
	// latArray()
	// latArray2()
	// latSlice1()
	// latSlice2()
	// latSlice3()
	// latSlice4()
	// latSlice5()
	// latLoop4()
	// latLoop5()
	// fmt.Println(getCoordinates(60,100))
	// fname, lname := getName()
	// fmt.Println(fname, lname)
	// fname, _ := getName()
	// fmt.Println(fname)
	// fmt.Println(persegi(10,5))
	// function06()
	// function06b()
	function06c()
}